schema_version: 1

context:
  name: "surface-apps"
  version: "0.0.0.dev0"  # This will be replaced by the actual version in the build process
  python_min: "3.10"
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, <2.0.dev
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoapps-utils >=0.6.0a, <0.7.dev
    - geoh5py >=0.12.0a, <0.13.dev
    # other direct dependencies
    - numpy >=1.26.0, <1.27.dev
    - pydantic >=2.5.2, <3.0.dev
    - scikit-image >=0.25.2, <0.26.dev
    - scipy >=1.14.0, <1.15.dev
    - tqdm >=4.66.1, <5.0.dev

tests:
  - python:
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

about:
  summary: Surface detection within geoscientific data.
  license: MIT
  license_file: LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/surface-apps

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
