name: Create JIRA issue

on:
  issues:
    types: [opened]

jobs:
  call-workflow-create-jira-issue:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-jira-issue_to_jira.yml@v3
    permissions:
      issues: write
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL_WRITE }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_WRITE }}
    with:
      project_key: 'GEOPY'
